#!/bin/sh
exec 2>&1

#java -jar /app/target/uberjar/discovery-cicd.jar server
#java -Dconfig.file=/app/bin/docker/serving-config/application.conf -jar /app/target/uberjar/discovery-cicd.jar server

java ${DISCOVERY_CICD_JAVA_OPTIONS} -jar /app/target/uberjar/discovery-cicd.jar server

